[package]
name = "uncommitted-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "uncommitted"
path = "src/main.rs"

[dependencies]
clap = { version = "3.1.15", features = ["derive"] }
flume = "0.10.12"
num_cpus = "1.13.1"
